routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\TeachersController;
use \App\Http\Controllers\SubjectsController;
use \App\Http\Controllers\ClassesController;
use \App\Http\Controllers\TimeTablesController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('Auth.login');
});

Auth::routes();

Route::get('/home', [HomeController::class, 'index'])->name('home');
Route::resource('teacher', TeachersController::class);
Route::resource('class', ClassesController::class);
Route::resource('subject', SubjectsController::class);
Route::resource('time-table', TimeTablesController::class);

app/Http/Controllers/TimeTablesController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\TimeTableRequest;
use App\Models\Classes;
use App\Models\Subjects;
use App\Models\Teachers;
use App\Models\TimeTables;
use Illuminate\Http\Request;
use Ramsey\Uuid\Type\Time;

class TimeTablesController extends Controller
{
    private $_messages = [
        'CREATE_SUCCESS' => 'Period Added to Time Table Successfully.',
        'UPDATE_SUCCESS' => 'Period Updated to Time Table  Successfully.',
        'DELETE_SUCCESS' => 'Period Deleted from Time Table  Successfully.',
        'DELETE_FAILED' => 'Failed to delete period from Time Table.',
    ];

    public function index()
    {
        $timeTables = TimeTables::with('classes')
            ->with('subjects')
            ->with('teachers')
            ->get();
        return view('pages.timeTable.index', compact('timeTables'));

    }

    public function create()
    {
        $classes = Classes::all();
        $subjects =Subjects::all();
        $teachers = Teachers::all();
        return view('pages.timeTable.create',[
            'classes' => $classes,
            'subjects' => $subjects,
            'teachers' => $teachers
        ]);
    }

    public function store(TimeTableRequest $request)
    {
        $request->validated();
        $timeTable = new TimeTables();
        $timeTable->class_id = $request->class_id;
        $timeTable->subject_id = $request->subject_id;
        $timeTable->teacher_id = $request->teacher_id;
        $timeTable->start_time = $request->start_time;
        $timeTable->end_time = $request->end_time;
        $timeTable->save();
        return redirect()->route('time-table.index')->with('success', $this->_messages['CREATE_SUCCESS']);
    }

    public function show(TimeTables $timeTables)
    {
        //
    }

    public function edit(TimeTables $timeTable)
    {
        $classes = Classes::all();
        $subjects = Subjects::all();
        $teachers = Teachers::all();
        return view('pages.timeTable.edit', [
            'subjects' => $subjects,
            'classes' =>$classes,
            'teachers' =>$teachers,
            'timeTable' =>$timeTable
        ]);
    }

    public function update(TimeTableRequest $request, TimeTables $timeTable)
    {
        $request->validated();
        $timeTable->class_id = $request->class_id;
        $timeTable->subject_id = $request->subject_id;
        $timeTable->teacher_id = $request->teacher_id;
        $timeTable->start_time = $request->start_time;
        $timeTable->end_time = $request->end_time;
        $timeTable->save();
        return redirect()->route('time-table.index')->with('success', $this->_messages['UPDATE_SUCCESS']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\TimeTables  $timeTables
     * @return \Illuminate\Http\Response
     */
    public function destroy(TimeTables $timeTable)
    {
        $timeTable->delete();
        return redirect()->route('time-table.index')->with('success', $this->_messages['DELETE_SUCCESS']);

    }
}

resources/views/Pages/timeTable/create.blade.php
@extends('layouts.app')
@section('content')
    <section>
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-8">
                    @include('partials.alert_message')

                    <div class="card">
                        <div class="card-header">
                                <span class="float-left-start">
                                    <a href="{{ route("time-table.index") }}"><i class="fa fa-arrow-left"></i>Back</a>
                                </span>
                            <h3 class="text-center">{{ __("Adding Period to Time Table") }}</h3>
                        </div>
                    </div>
                    <div class="card-body bg-white py-5 form-block">
                        <div class="row">
                            <div class="col-8 mx-auto">
                                <form method="POST" action="{{ route('time-table.store')}}">
                                    @csrf
                                    <div class="form-group row">
                                        <label class="col-12 col-md-2 col-form-label">Class </label>
                                        <div class="col-12 col-md-8">
                                            <select class="form-control" name="class_id">
                                                @if(isset($classes) && $classes)
                                                    <option value="">Select Class</option>
                                                    @foreach($classes as $key=>$class)
                                                        <option
                                                            @if(old('class_id') == $class->id) selected
                                                            @endif
                                                            value="{{ $class->id }}">{{ $class->name }}</option>
                                                    @endforeach
                                                @else
                                                    <option>Please Add Class !</option>
                                                @endif
                                            </select>
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label class="col-12 col-md-2 col-form-label">Subjects </label>
                                        <div class="col-12 col-md-8">
                                            <select class="form-control" name="subject_id">
                                                @if(isset($subjects) && $subjects)
                                                    <option value="">Select Subject</option>
                                                    @foreach($subjects as $key=>$subject)
                                                        <option
                                                            @if(old('subject_id') == $subject->id) selected
                                                            @endif
                                                            value="{{ $subject->id }}">{{ $subject->name }}</option>
                                                    @endforeach
                                                @else
                                                    <option>Please Add Subject !</option>
                                                @endif
                                            </select>
                                        </div>
                                    </div>

                                    <div class="form-group row">
                                        <label class="col-12 col-md-2 col-form-label">Teachers </label>
                                        <div class="col-12 col-md-8">
                                            <select class="form-control" name="teacher_id">
                                                @if(isset($teachers) && $teachers)
                                                    <option value="">Select Teacher</option>
                                                    @foreach($teachers as $key=>$teacher)
                                                        <option
                                                            @if(old('teacher_id') == $teacher->id) selected
                                                            @endif
                                                            value="{{ $teacher->id }}">{{ $teacher->name }}</option>
                                                    @endforeach
                                                @else
                                                    <option>Please Add Teacher !</option>
                                                @endif
                                            </select>
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label class="col-12 col-md-2 col-form-label">Start Time </label>
                                        <div class="col-12 col-md-8">
                                            <input class="form-control" type="time" name="start_time"
                                                   value="{{ old('start_time') }}"/>
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label class="col-12 col-md-2 col-form-label">End Time </label>
                                        <div class="col-12 col-md-8">
                                            <input class="form-control" type="time" name="end_time"
                                                   value="{{ old('end_time') }}"/>
                                        </div>
                                    </div>
                                    <hr>

                                    <div class="text-center">
                                        <input type="submit" value="Create" class="btn btn-outline-primary"/>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/Pages/timeTable/edit.blade.php
@extends('layouts.app')
@section('content')
    <section>
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-8">
                    @include('partials.alert_message')

                    <div class="card">
                        <div class="card-header">
                                <span class="float-left-start">
                                    <a href="{{ route("time-table.index") }}"><i class="fa fa-arrow-left"></i>Back</a>
                                </span>
                            <h3 class="text-center">{{ __("Updating Period to Time Table") }}</h3>
                        </div>
                    </div>
                    <div class="card-body bg-white py-5 form-block">
                        <div class="row">
                            <div class="col-8 mx-auto">
                                <form method="POST" action="{{ route('time-table.update',$timeTable->id)}}">
                                    @csrf
                                    @method('PUT')
                                    <div class="form-group row">
                                        <label class="col-12 col-md-2 col-form-label">Class </label>
                                        <div class="col-12 col-md-8">
                                            <select class="form-control" name="class_id">
                                                @if(isset($classes) && $classes)
                                                    <option value="">Select Class</option>
                                                    @foreach($classes as $key=>$class)
                                                        <option
                                                            @if(old('class_id') == $class->id) selected
                                                            @elseif($timeTable->class_id == $class->id) selected
                                                            @endif
                                                            value="{{ $class->id }}">{{ $class->name }}</option>
                                                    @endforeach
                                                @else
                                                    <option>Please Add Class !</option>
                                                @endif
                                            </select>
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label class="col-12 col-md-2 col-form-label">Subjects </label>
                                        <div class="col-12 col-md-8">
                                            <select class="form-control" name="subject_id">
                                                @if(isset($subjects) && $subjects)
                                                    <option value="">Select Subject</option>
                                                    @foreach($subjects as $key=>$subject)
                                                        <option
                                                            @if(old('subject_id') == $subject->id) selected
                                                            @elseif($timeTable->subject_id == $subject->id) selected
                                                            @endif
                                                            value="{{ $subject->id }}">{{ $subject->name }}</option>
                                                    @endforeach
                                                @else
                                                    <option>Please Add Subject !</option>
                                                @endif
                                            </select>
                                        </div>
                                    </div>

                                    <div class="form-group row">
                                        <label class="col-12 col-md-2 col-form-label">Teachers </label>
                                        <div class="col-12 col-md-8">
                                            <select class="form-control" name="teacher_id">
                                                @if(isset($teachers) && $teachers)
                                                    <option value="">Select Teacher</option>
                                                    @foreach($teachers as $key=>$teacher)
                                                        <option
                                                            @if(old('teacher_id') == $teacher->id) selected
                                                            @elseif($timeTable->teacher_id == $teacher->id) selected
                                                            @endif
                                                            value="{{ $teacher->id }}">{{ $teacher->name }}</option>
                                                    @endforeach
                                                @else
                                                    <option>Please Add Teacher !</option>
                                                @endif
                                            </select>
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label class="col-12 col-md-2 col-form-label">Start Time </label>
                                        <div class="col-12 col-md-8">
                                            <input class="form-control" type="time" name="start_time"
                                                   value="{{ old('start_time') ? old('start_time') : $teacher->start_time }}"/>
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label class="col-12 col-md-2 col-form-label">End Time </label>
                                        <div class="col-12 col-md-8">
                                            <input class="form-control" type="time" name="end_time"
                                                   value="{{ old('end_time') ? old('end_time') : $teacher->end_time }}"/>
                                        </div>
                                    </div>
                                    <hr>

                                    <div class="text-center">
                                        <input type="submit" value="Update" class="btn btn-outline-primary"/>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/Pages/timeTable/index.blade.php
@extends('layouts.app')
@section('content')
    <section>
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-8">
                    @include('partials.alert_message')

                    <div class="card">
                        <div class="card-header">
                            <h2 class="float-lg-start">Time Table</h2><span>
                                 <a class="float-lg-end btn btn-primary"
                                    href="{{ route('time-table.create') }}">
                                ADD <i class="fa fa-plus fa-icon"></i>
                            </a>
                            </span>

                        </div>
                    </div>
                    <div class="card-body bg-white">
                        <div class="row">
                            <div class="col-12">
                                <table class="table table-bordered table-striped">
                                    <thead>
                                    <tr class="table-lighter-blue">
                                        <th scope="col">#</th>
                                        <th scope="col">Class Id</th>
                                        <th scope="col">Subject Id</th>
                                        <th scope="col">Teacher Id</th>
                                        <th scope="col">Timing</th>
                                        <th scope="col" colspan="2" class="text-center">Action</th>
                                    </tr>
                                    </thead>
                                    <tbody>

                                    @if($timeTables)
                                        @foreach($timeTables as $key=>$timeTable)
                                            <tr>
                                                <td>
                                                    {{++$key}}
                                                </td>
                                                <td>
                                                    {{$timeTable->classes->name}}
                                                </td>
                                                <td>
                                                    {{$timeTable->subjects->name}}
                                                </td>
                                                <td>
                                                    {{$timeTable->teachers->name}}
                                                </td>
                                                <td>
                                                    {{$timeTable->start_time}} 'to' {{$timeTable->end_time}}
                                                </td>
                                                <td>
                                                    <a href="{{ route('time-table.edit',$timeTable->id) }}"
                                                    ><i class="fa fa-pencil-alt"></i> Edit</a>
                                                    <form class="d-inline-block"
                                                          action="{{ route('time-table.destroy',$timeTable->id) }}"
                                                          method="POST" class="d-block mb-0">
                                                        {{ csrf_field() }}
                                                        {{ method_field('DELETE') }}
                                                        <button type="submit"><i
                                                                class="fa fa-trash"></i> Delete
                                                        </button>
                                                    </form>
                                                </td>
                                            </tr>
                                        @endforeach
                                    @endif

                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        </div>

    </section>
@endsection