routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\TeachersController;
use \App\Http\Controllers\SubjectsController;
use \App\Http\Controllers\ClassesController;
use \App\Http\Controllers\TimeTablesController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('Auth.login');
});

Auth::routes();

Route::get('/home', [HomeController::class, 'index'])->name('home');
Route::resource('teacher', TeachersController::class);
Route::resource('class', ClassesController::class);
Route::resource('subject', SubjectsController::class);
Route::resource('time-table', TimeTablesController::class);

app/Http/Controllers/ClassesController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\ClassRequest;
use App\Models\Classes;
use App\Models\Subjects;
use App\Models\TimeTables;
use Illuminate\Http\Request;

class ClassesController extends Controller
{
    private $_messages = [
        'CREATE_SUCCESS' => 'Class Added Successfully.',
        'UPDATE_SUCCESS' => 'Class Updated Successfully.',
        'DELETE_SUCCESS' => 'Class Deleted Successfully.',
        'DELETE_FAILED' => 'Failed to delete.',
        'DELETE_CONSTRAINT' =>"Failed to Delete Class already in Use"
    ];

    public function index()
    {
        $classes = Classes::all();
        return view('pages.classes.index', compact('classes'));
    }

    public function create()
    {
        return view('pages.classes.create');
    }

    public function store(ClassRequest $request)
    {
        $request->validated();
        $teacher = new Classes();
        $teacher->name = $request->name;
        $teacher->save();
        return redirect()->route('class.index')->with('success', $this->_messages['CREATE_SUCCESS']);
    }

    public function show(Classes $classes)
    {
        //
    }

    public function edit(Classes $class)
    {
        return view('pages.classes.edit', [
            'class' => $class
        ]);
    }

    public function update(ClassRequest $request, Classes $classes)
    {
        $request->validated();
        $classes->name = $request->name;
        $classes->save();
        return redirect()->route('class.index')->with('success', $this->_messages['UPDATE_SUCCESS']);
    }

    public function destroy(Classes $class)
    {
        $subject = Subjects::where('class_id', $class->id);
        if ($subject) {
            return redirect()->route('class.index')->with('failed', $this->_messages['DELETE_CONSTRAINT']);
        }
        $timeTable = TimeTables::where('class_id', $class->id);
        if ($timeTable) {
            return redirect()->route('time-table.index')->with('failed', $this->_messages['DELETE_CONSTRAINT']);
        }
        $class->delete();
        return redirect()->route('class.index')->with('success', $this->_messages['DELETE_SUCCESS']);
    }
}

resources/views/Pages/classes/create.blade.php
@extends('layouts.app')
@section('content')
    <section>
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-8">
                    @include('partials.alert_message')

                    <div class="card">
                        <div class="card-header">
                                <span class="float-left-start">
                                    <a href="{{ route("class.index") }}"><i class="fa fa-arrow-left"></i>Back</a>
                                </span>
                            <h3 class="text-center">{{ __("Add Class") }}</h3>
                        </div>
                    </div>
                    <div class="card-body bg-white py-5 form-block">
                        <div class="row">
                            <div class="col-8 mx-auto">
                                <form method="POST" action="{{ route('class.store') }}">
                                    @csrf
                                    <div class="form-group row">
                                        <label class="col-12 col-md-2 col-form-label">Name </label>
                                        <div class="col-12 col-md-8">
                                            <input class="form-control" type="text" name="name"
                                                   value="{{ old('name') }}" placeholder="Enter Class Name"/>
                                        </div>
                                    </div>

                                    <hr>

                                    <div class="text-center">
                                        <input type="submit" value="Create Class" class="btn btn-outline-primary"/>
                                    </div>

                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </section>
@endsection

resources/views/Pages/classes/edit.blade.php
@extends('layouts.app')
@section('content')
    <section>
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-8">
                    @include('partials.alert_message')

                    <div class="card">
                        <div class="card-header">
                                <span class="float-left-start">
                                    <a href="{{ route("class.index") }}"><i class="fa fa-arrow-left"></i>Back</a>
                                </span>
                            <h3 class="text-center">{{ __("Update Class") }}</h3>
                        </div>
                    </div>
                    <div class="card-body bg-white py-5 form-block">
                        <div class="row">
                            <div class="col-8 mx-auto">
                                <form method="POST" action="{{ route('class.update',$class->id) }}">
                                    @csrf
                                    @method('PUT')
                                    <div class="form-group row">
                                        <label class="col-12 col-md-2 col-form-label">Name </label>
                                        <div class="col-12 col-md-8">
                                            <input class="form-control" type="text" name="name"
                                                   value="{{ old('name') ? old('name') : $class->name }}"/>
                                        </div>
                                    </div>
                                    <hr>

                                    <div class="text-center">
                                        <input type="submit" value="Update Class" class="btn btn-outline-primary"/>
                                    </div>

                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/Pages/classes/index.blade.php
@extends('layouts.app')
@section('content')
    <section>
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-6">
                    @include('partials.alert_message')

                    <div class="card">
                        <div class="card-header">
                            <h2 class="float-lg-start">Class</h2><span>
                                 <a class="float-lg-end btn btn-primary"
                                    href="{{ route('class.create') }}">
                                ADD <i class="fa fa-plus fa-icon"></i>
                            </a>
                            </span>

                        </div>
                    </div>
                    <div class="card-body bg-white">
                        <div class="row">
                            <div class="col-12">
                                <table class="table table-bordered table-striped">
                                    <thead>
                                    <tr class="table-lighter-blue">
                                        <th scope="col">#</th>
                                        <th scope="col">NAME</th>
                                        <th scope="col" class="text-center">Action</th>
                                    </tr>
                                    </thead>
                                    <tbody>

                                    @if($classes)
                                        @foreach($classes as $key=>$class)
                                            <tr>
                                                <td>
                                                    {{++$key}}
                                                </td>
                                                <td>
                                                    {{$class->name}}
                                                </td>
                                                <td class="text-center">
                                                    <a class="" href="{{ route('class.edit',$class->id) }}"
                                                    ><i class="fa fa-pencil-alt"></i> Edit</a>
                                                    <form class="d-inline-block"
                                                          action="{{ route('class.destroy',$class->id) }}"
                                                          method="POST" class="d-block mb-0">
                                                        {{ csrf_field() }}
                                                        {{ method_field('DELETE') }}
                                                        <button type="submit"><i
                                                                class="fa fa-trash "></i> Delete
                                                        </button>
                                                    </form>
                                                </td>
                                            </tr>
                                        @endforeach
                                    @endif

                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        </div>

    </section>
@endsection