routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\TeachersController;
use \App\Http\Controllers\SubjectsController;
use \App\Http\Controllers\ClassesController;
use \App\Http\Controllers\TimeTablesController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('Auth.login');
});

Auth::routes();

Route::get('/home', [HomeController::class, 'index'])->name('home');
Route::resource('teacher', TeachersController::class);
Route::resource('class', ClassesController::class);
Route::resource('subject', SubjectsController::class);
Route::resource('time-table', TimeTablesController::class);

app/Models/Teachers.php
<?php

namespace App\Models;

use App\Http\Controllers\TimeTablesController;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Teachers extends Model
{
    use HasFactory;
    public function time_schedule()
    {
        return $this->hasMany(TimeTables::class, 'teacher_id');
    }
}

app/Http/Controllers/TeachersController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateTeacherRequest;
use App\Models\Teachers;
use App\Models\TimeTables;
use Illuminate\Http\Request;
use Ramsey\Uuid\Type\Time;

class TeachersController extends Controller
{
    private $_messages = [
        'CREATE_SUCCESS' => 'Teacher Added Successfully.',
        'UPDATE_SUCCESS' => 'Teacher Updated Successfully.',
        'DELETE_SUCCESS' => 'Teacher Deleted Successfully.',
        'DELETE_CONSTRAINT' =>"Failed to Delete Teacher already in Use",
        'DELETE_FAILED' => 'Failed to delete.',
    ];

    public function index()
    {
        $teachers = Teachers::all();

        return view('pages.teachers.index', compact('teachers'));
    }

    public function create()
    {
        return view('pages.teachers.create');
    }

    public function store(CreateTeacherRequest $request)
    {
        $request->validated();
        $teacher = new Teachers();
        $teacher->name = $request->name;
        $teacher->qualification = $request->qualification;
        $teacher->start_time = $request->start_time;
        $teacher->end_time = $request->end_time;
        $teacher->save();
        return redirect()->route('teacher.index')->with('success', $this->_messages['CREATE_SUCCESS']);

    }

    public function show(Teachers $teacher)
    {
        //
        $time_table = Teachers::with('time_schedule')->where('id', '=',$teacher->id)->get()->first();
        return view('pages.teachers.show', [
            'time_table' => $time_table
        ]);
    }

    public function edit(Teachers $teacher)
    {
        return view('pages.teachers.edit', [
            'teacher' => $teacher
        ]);
    }

    public function update(CreateTeacherRequest $request, Teachers $teacher)
    {
        // Validation
        $request->validated();
        $teacher->name = $request->name;
        $teacher->qualification = $request->qualification;
        $teacher->start_time = $request->start_time;
        $teacher->end_time = $request->end_time;
        $teacher->save();
        return redirect()->route('teacher.index')->with('success', $this->_messages['UPDATE_SUCCESS']);

    }

    public function destroy(Teachers $teacher)
    {
        $timeTable = TimeTables::where('class_id', $teacher->id);
        if ($timeTable) {
            return redirect()->route('time-table.index')->with('failed', $this->_messages['DELETE_CONSTRAINT']);
        }
        $teacher->delete();
        return redirect()->route('teacher.index')->with('success', $this->_messages['DELETE_SUCCESS']);
        //
    }
}

resources/views/Pages/teachers/create.blade.php
@extends('layouts.app')
@section('content')
    <section>
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-8">
                    @include('partials.alert_message')

                    <div class="card">
                        <div class="card-header">
                                <span class="float-left-start">
                                    <a href="{{ route("teacher.index") }}"><i class="fa fa-arrow-left"></i>Back</a>
                                </span>
                            <h3 class="text-center">{{ __("Add Teacher") }}</h3>
                        </div>
                    </div>
                    <div class="card-body bg-white py-5 form-block">
                        <div class="row">
                            <div class="col-8 mx-auto">
                                <form method="POST" action="{{ route('teacher.store') }}">
                                    @csrf
                                    <div class="form-group row">
                                        <label class="col-12 col-md-2 col-form-label">Name </label>
                                        <div class="col-12 col-md-8">
                                            <input class="form-control" type="text" name="name"
                                                   value="{{ old('name') }}" placeholder="Enter Name"/>
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label class="col-12 col-md-2 col-form-label">Qualification </label>
                                        <div class="col-12 col-md-8">
                                            <input class="form-control" type="text" name="qualification"
                                                   value="{{ old('qualification') }}"
                                                   placeholder="Enter Qualification"/>
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label class="col-12 col-md-2 col-form-label">Start Time </label>
                                        <div class="col-12 col-md-8">
                                            <input class="form-control" type="time" name="start_time"
                                                   value="{{ old('start_time') }}" placeholder="Enter Starting Time"/>
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label class="col-12 col-md-2 col-form-label">End Time </label>
                                        <div class="col-12 col-md-8">
                                            <input class="form-control" type="time" name="end_time"
                                                   value="{{ old('end_time') }}" placeholder="Enter Ending Time"/>
                                        </div>
                                    </div>

                                    <hr>

                                    <div class="text-center">
                                        <input type="submit" value="Create Teacher" class="btn btn-outline-primary"/>
                                    </div>

                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </section>
@endsection

resources/views/Pages/teachers/edit.blade.php
@extends('layouts.app')
@section('content')
    <section>
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-8">
                    @include('partials.alert_message')

                    <div class="card">
                        <div class="card-header">
                                <span class="float-left-start">
                                    <a href="{{ route("teacher.index") }}"><i class="fa fa-arrow-left"></i>Back</a>
                                </span>
                            <h3 class="text-center">{{ __("Update Teacher") }}</h3>
                        </div>
                    </div>
                    <div class="card-body bg-white py-5 form-block">
                        <div class="row">
                            <div class="col-8 mx-auto">
                                <form method="POST" action="{{ route('teacher.update',$teacher->id) }}">
                                    @csrf
                                    @method('PUT')
                                    <div class="form-group row">
                                        <label class="col-12 col-md-2 col-form-label">Name </label>
                                        <div class="col-12 col-md-8">
                                            <input class="form-control" type="text" name="name"
                                                   value="{{ old('name') ? old('name') : $teacher->name }}"/>
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label class="col-12 col-md-2 col-form-label">Qualification </label>
                                        <div class="col-12 col-md-8">
                                            <input class="form-control" type="text" name="qualification"
                                                   value="{{ old('qualification') ? old('qualification') : $teacher->qualification }}" />
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label class="col-12 col-md-2 col-form-label">Start Time </label>
                                        <div class="col-12 col-md-8">
                                            <input class="form-control" type="time" name="start_time"
                                                   value="{{ old('start_time') ? old('start_time') : $teacher->start_time }}"/>
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label class="col-12 col-md-2 col-form-label">End Time </label>
                                        <div class="col-12 col-md-8">
                                            <input class="form-control" type="time" name="end_time"
                                                   value="{{ old('end_time') ? old('end_time') : $teacher->end_time }}"/>
                                        </div>
                                    </div>

                                    <hr>

                                    <div class="text-center">
                                        <input type="submit" value="Update Teacher" class="btn btn-outline-primary"/>
                                    </div>

                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/Pages/teachers/index.blade.php
@extends('layouts.app')
@section('content')
    <section>
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-8">
                    @include('partials.alert_message')

                    <div class="card">
                        <div class="card-header">
                            <h2 class="float-lg-start">Teachers</h2><span>
                                 <a class="float-lg-end btn btn-primary"
                                    href="{{ route('teacher.create') }}">
                                ADD <i class="fa fa-plus fa-icon"></i>
                            </a>
                            </span>

                        </div>
                    </div>
                    <div class="card-body bg-white">
                        <div class="row">
                            <div class="col-12">
                                <table class="table table-bordered table-striped">
                                    <thead>
                                    <tr class="table-lighter-blue">
                                        <th scope="col">#</th>
                                        <th scope="col">NAME</th>
                                        <th scope="col">Qualification</th>
                                        <th scope="col">Timing</th>
                                        <th scope="col" colspan="2" class="text-center">Action</th>
                                    </tr>
                                    </thead>
                                    <tbody>

                                    @if($teachers)
                                        @foreach($teachers as $key=>$teacher)
                                            <tr>
                                                <td>
                                                    {{++$key}}
                                                </td>
                                                <td>
                                                    {{$teacher->name}}
                                                </td>
                                                <td>
                                                    {{$teacher->qualification}}
                                                </td>
                                                <td>
                                                    {{$teacher->start_time}} 'to' {{$teacher->end_time}}
                                                </td>
                                                <td>
                                                    <a href="{{ route('teacher.show',$teacher->id) }}"
                                                       class="btn btn-link">
                                                        <i class="fa fa-eye"></i> View Schedule
                                                    </a>
                                                    <a href="{{ route('teacher.edit',$teacher->id) }}"
                                                    ><i class="fa fa-pencil-alt"></i> Edit</a>
                                                    <form class="d-inline-block"
                                                          action="{{ route('teacher.destroy',$teacher->id) }}"
                                                          method="POST" class="d-block mb-0">
                                                        {{ csrf_field() }}
                                                        {{ method_field('DELETE') }}
                                                        <button type="submit"><i
                                                                class="fa fa-trash"></i> Delete
                                                        </button>
                                                    </form>
                                                </td>
                                            </tr>
                                        @endforeach
                                    @endif

                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        </div>

    </section>
@endsection

resources/views/Pages/teachers/show.blade.php
@extends('layouts.app')
@section('content')
    <section>
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-8">
                    @include('partials.alert_message')

                    <div class="card">
                        <div class="row px-3">
                            <div class="col-12 py-4">
                                <h2 class="float-lg-start">Teacher Details</h2>
                            </div>
                            <div class="col-12 col-md-4">
                                {{ "Name :" .$time_table->name }}
                            </div>
                            <div class="col-12 col-md-4">
                                {{ "Qualification :" .$time_table->qualification }}
                            </div>
                            <div class="col-12 col-md-4">
                                {{ "Timing :" .\Carbon\Carbon::parse($time_table->start_time)->format('H:i') ."-". \Carbon\Carbon::parse($time_table->end_time)->format('H:i') }}
                            </div>
                        </div>
                        <div class="card-body bg-white">
                            <div class="row">
                                <div class="col-12 py-4">
                                    <h2 class="float-lg-start">Schedule:</h2>
                                </div>
                                <div class="col-12">
                                    <table class="table table-bordered table-striped">
                                        <thead>
                                        <tr class="table-lighter-blue">
                                            <th scope="col">#</th>
                                            <th scope="col">Class</th>
                                            <th scope="col">Subject</th>
                                            <th scope="col">Timing</th>
                                            <th scope="col">Duration</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        @if($time_table)
                                            @foreach($time_table['time_schedule'] as $key=>$timeTable)
                                                <tr>
                                                    <td>
                                                        {{++$key}}
                                                    </td>
                                                    <td>
                                                        {{$timeTable->classes->name}}
                                                    </td>
                                                    <td>
                                                        {{$timeTable->subjects->name}}
                                                    </td>
                                                    <td>
                                                        {{\Carbon\Carbon::parse($timeTable->start_time)->format('H:i')}}  - {{\Carbon\Carbon::parse($timeTable->end_time)->format('H:i')}}
                                                    </td>

                                                    <td>
                                                        {{ \Carbon\Carbon::parse($timeTable->start_time)->diffInMinutes(\Carbon\Carbon::parse($timeTable->end_time)) }}
                                                    </td>
                                                </tr>
                                            @endforeach
                                        @endif

                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </section>
@endsection