routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\TeachersController;
use \App\Http\Controllers\SubjectsController;
use \App\Http\Controllers\ClassesController;
use \App\Http\Controllers\TimeTablesController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('Auth.login');
});

Auth::routes();

Route::get('/home', [HomeController::class, 'index'])->name('home');
Route::resource('teacher', TeachersController::class);
Route::resource('class', ClassesController::class);
Route::resource('subject', SubjectsController::class);
Route::resource('time-table', TimeTablesController::class);

app/Models/Subjects.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Subjects extends Model
{
    use HasFactory;
    public function classDetails(){
        return $this->belongsTo(Classes::class, 'class_id');
    }
}

app/Http/Controllers/SubjectsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\SubjectRequest;
use App\Models\Classes;
use App\Models\Subjects;
use App\Models\TimeTables;
use Illuminate\Http\Request;

class SubjectsController extends Controller
{
    private $_messages = [
        'CREATE_SUCCESS' => 'Subject Added Successfully.',
        'UPDATE_SUCCESS' => 'Subject Updated Successfully.',
        'DELETE_SUCCESS' => 'Subject Deleted Successfully.',
        'DELETE_CONSTRAINT' =>"Failed to Delete Subject already in Use",
        'DELETE_FAILED' => 'Failed to delete.',
    ];

    public function index()
    {
        $subjects = Subjects::all();
        return view('pages.subjects.index', compact('subjects'));
    }

    public function create()
    {
        $classes = Classes::all();
        return view('pages.subjects.create',compact('classes'));
    }

    public function store(SubjectRequest $request)
    {
        $request->validated();
        $subject = new Subjects();
        $subject->name = $request->name;
        $subject->code = $request->code;
        $subject->class_id = $request->class_id;
        $subject->save();
        return redirect()->route('subject.index')->with('success', $this->_messages['CREATE_SUCCESS']);
    }

    public function show(Subjects $subject)
    {
        //
    }

    public function edit(Subjects $subject)
    {
        $classes = Classes::all();
        return view('pages.subjects.edit', [
            'subject' => $subject,
            'classes' =>$classes
        ]);
    }

    public function update(SubjectRequest $request, Subjects $subject)
    {
        $request->validated();
        $subject->name = $request->name;
        $subject->code = $request->code;
        $subject->class_id = $request->class_id;
        $subject->save();
        return redirect()->route('subject.index')->with('success', $this->_messages['UPDATE_SUCCESS']);
    }

    public function destroy(Subjects $subject)
    {
        $timeTable = TimeTables::where('subject_id', $subject->id);
        if ($timeTable) {
            return redirect()->route('time-table.index')->with('failed', $this->_messages['DELETE_CONSTRAINT']);
        }
        $subject->delete();
        return redirect()->route('subject.index')->with('success', $this->_messages['DELETE_SUCCESS']);
    }
}

resources/views/Pages/subjects/create.blade.php
@extends('layouts.app')
@section('content')
    <section>
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-8">
                    @include('partials.alert_message')

                    <div class="card">
                        <div class="card-header">
                                <span class="float-left-start">
                                    <a href="{{ route("subject.index") }}"><i class="fa fa-arrow-left"></i>Back</a>
                                </span>
                            <h3 class="text-center">{{ __("Add Subject") }}</h3>
                        </div>
                    </div>
                    <div class="card-body bg-white py-5 form-block">
                        <div class="row">
                            <div class="col-8 mx-auto">
                                <form method="POST" action="{{ route('subject.store') }}">
                                    @csrf
                                    <div class="form-group row">
                                        <label class="col-12 col-md-2 col-form-label">Name </label>
                                        <div class="col-12 col-md-8">
                                            <input class="form-control" type="text" name="name"
                                                   value="{{ old('name') }}" placeholder="Enter Name"/>
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label class="col-12 col-md-2 col-form-label">Code </label>
                                        <div class="col-12 col-md-8">
                                            <input class="form-control" type="text" name="code"
                                                   value="{{ old('code') }}"
                                                   placeholder="Enter Code"/>
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label class="col-12 col-md-2 col-form-label">Class </label>
                                        <div class="col-12 col-md-8">
                                            <select class="form-control" name="class_id">
                                                @if(isset($classes) && $classes)
                                                    <option value="">Select Class</option>
                                                    @foreach($classes as $key=>$class)
                                                        <option
                                                            @if(old('class_id') == $class->id) selected
                                                            @endif
                                                            value="{{ $class->id }}">{{ $class->name }}</option>
                                                    @endforeach
                                                @else
                                                    <option>Please Add Class !</option>
                                                @endif
                                            </select>
                                        </div>
                                    </div>

                                    <hr>

                                    <div class="text-center">
                                        <input type="submit" value="Create Subject" class="btn btn-outline-primary"/>
                                    </div>

                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </section>
@endsection

resources/views/Pages/subjects/edit.blade.php
@extends('layouts.app')
@section('content')
    <section>
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-8">
                    @include('partials.alert_message')
                    <div class="card">
                        <div class="card-header">
                                <span class="float-left-start">
                                    <a href="{{ route("subject.index") }}"><i class="fa fa-arrow-left"></i>Back</a>
                                </span>
                            <h3 class="text-center">{{ __("Update Subject") }}</h3>
                        </div>
                    </div>
                    <div class="card-body bg-white py-5 form-block">
                        <div class="row">
                            <div class="col-8 mx-auto">
                                <form method="POST" action="{{ route('subject.update', $subject->id) }}">
                                    @csrf
                                    @method('PUT')
                                    <div class="form-group row">
                                        <label class="col-12 col-md-2 col-form-label">Name </label>
                                        <div class="col-12 col-md-8">
                                            <input class="form-control" type="text" name="name"
                                                   value="{{ old('name') ? old('name') : $subject->name }}" />
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label class="col-12 col-md-2 col-form-label">Code </label>
                                        <div class="col-12 col-md-8">
                                            <input class="form-control" type="text" name="code"
                                                   value="{{ old('code') ? old('code') : $subject->code }}"/>
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label class="col-12 col-md-2 col-form-label">Class </label>
                                        <div class="col-12 col-md-8">
                                            <select class="form-control" name="class_id">
                                                @if(isset($classes) && $classes)
                                                    <option value="">Select Class</option>
                                                    @foreach($classes as $key=>$class)
                                                        <option
                                                            @if(old('class_id') == $class->id) selected
                                                            @elseif($subject->class_id == $class->id) selected
                                                            @endif
                                                            value="{{ $class->id }}">{{ $class->name }}</option>
                                                    @endforeach
                                                @else
                                                    <option>Please Add Class !</option>
                                                @endif
                                            </select>
                                        </div>
                                    </div>

                                    <hr>

                                    <div class="text-center">
                                        <input type="submit" value="Update Subject" class="btn btn-outline-primary"/>
                                    </div>

                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </section>
@endsection

resources/views/Pages/subjects/index.blade.php
@extends('layouts.app')
@section('content')
    <section>
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-8">
                    @include('partials.alert_message')

                    <div class="card">
                        <div class="card-header">
                            <h2 class="float-lg-start">Subjects</h2><span>
                                 <a class="float-lg-end btn btn-primary"
                                    href="{{ route('subject.create') }}">
                                ADD <i class="fa fa-plus fa-icon"></i>
                            </a>
                            </span>

                        </div>
                    </div>
                    <div class="card-body bg-white">
                        <div class="row">
                            <div class="col-12">
                                <table class="table table-bordered table-striped">
                                    <thead>
                                    <tr class="table-lighter-blue">
                                        <th scope="col">#</th>
                                        <th scope="col">Subject</th>
                                        <th scope="col">Subject Code</th>
                                        <th scope="col">Class</th>
                                        <th scope="col" colspan="2" class="text-center">Action</th>
                                    </tr>
                                    </thead>
                                    <tbody>

                                    @if($subjects)
                                        @foreach($subjects as $key=>$subject)
                                            <tr>
                                                <td>
                                                    {{++$key}}
                                                </td>
                                                <td>
                                                    {{$subject->name}}
                                                </td>
                                                <td>
                                                    {{$subject->code}}
                                                </td>
                                                <td>
                                                    {{$subject->classDetails->name}}
                                                </td>
                                                <td>
                                                    <a href="{{ route('subject.edit',$subject->id) }}"
                                                    ><i class="fa fa-pencil-alt"></i> Edit</a>
                                                    <form class="d-inline-block"
                                                          action="{{ route('subject.destroy',$subject->id) }}"
                                                          method="POST" class="d-block mb-0">
                                                        {{ csrf_field() }}
                                                        {{ method_field('DELETE') }}
                                                        <button type="submit"><i
                                                                class="fa fa-trash"></i> Delete
                                                        </button>
                                                    </form>
                                                </td>
                                            </tr>
                                        @endforeach
                                    @endif

                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        </div>

    </section>
@endsection